# **HOTEL BOOKING ANALYSIS**




##### **Project Type**    - EDA
##### **Contribution**    - Team
##### **Team Member 1 -**Dharmendra Yadav
##### **Team Member 2 -**Kratika Jawariya
##### **Team Member 3 -**Pranita tiwari


# **Project Summary**


The objective of this project is to conduct Exploratory Data Analysis (EDA) on a dataset related to hotel bookings.  By performing thorough exploratory analysis, we aim to uncover patterns, trends, and relationships within the dataset, which can provide valuable information to enhance decision-making processes in the hospitality industry.
The analysis focuses on several key aspects, including booking analysis, cancellation analysis, average daily rate (ADR) analysis, and customer retention.

#### **Data wrangling**:
The project begins with data wrangling tasks to ensure the data is in a suitable format for analysis. The data will be preprocessed to handle missing values, Removing duplicated columns, Created new columns and Changing data types. Relevant data cleaning techniques will be applied to ensure the quality of the dataset. Once the data wrangling phase is complete, the project moves on to the exploratory data analysis.

#### **Exploratory Data Analysis**:
The core phase of the project will involve conducting a comprehensive exploratory analysis. Throughout the analysis, visualizations using matplotlib and seaborn are employed to present the findings effectively. These visualizations aid in the interpretation and communication of the insights derived from the data. This will include investigating correlations between variables, identifying trends over time, and exploring patterns in customer behavior.

We will do the following type of analysis on our dataset:

**1. Customer Demographics**:

The analysis included factors such as customer nationality, market segments, and customer types (transient, contract, group). These insights can help tailor marketing strategies and target specific customer segments effectively.
Booking Patterns:

Understanding booking patterns, such as lead time, booking duration, and booking changes, provides insights into customer behavior and preferences. This information can guide revenue management strategies and optimize booking processes.

**2. Distribution Channels:**

The analysis examined different distribution channels, including online travel agents (OTA), direct bookings, and global distribution systems (GDS). Insights on revenue generation and booking cancellations from various channels can help hotels optimize their distribution strategies and improve revenue streams.

**3. Cancellations:**

The analysis delved into the reasons behind booking cancellations, exploring factors such as waiting time, lead time, and room type allocation. Identifying significant cancellation percentages for specific distribution channels (e.g., OTA) highlights areas for improvement and potential revenue loss.

**4. Revenue Generation:**

The analysis compared average daily rates (ADR) for different hotels, distribution channels, and months. Understanding revenue generation patterns can assist in pricing strategies, optimizing channel mix, and capitalizing on high-demand periods.

**5. Seasonal Trends:**

The analysis uncovered seasonal trends in terms of the number of guests, revenue, and ADR. Identifying peak months, such as August, can help hotels allocate resources effectively, manage staff levels, and tailor marketing campaigns to maximize occupancy and revenue during these periods.
The gained insights can positively impact the business in several ways:

**6. Data-Driven Decision-Making:**

By leveraging the insights from the analysis, hotels can make informed decisions based on data, enabling them to optimize pricing strategies, allocate resources effectively, and improve overall operational efficiency.
Revenue Management:

Understanding the factors influencing revenue generation, such as distribution channels and seasonal trends, empowers hotels to implement effective revenue management strategies. This includes adjusting pricing, managing inventory, and targeting specific customer segments to maximize revenue potential.

**7. Enhanced Customer Experience:**

The analysis of customer demographics and booking patterns provides valuable insights into customer preferences and behaviors. Hotels can use this information to tailor their services, improve guest experiences, and build customer loyalty.

**8. Marketing and Distribution Optimization:**

Insights on distribution channel performance, cancellation rates, and revenue generation can guide hotels in optimizing their marketing and distribution strategies. This may involve strengthening partnerships with high-performing channels, improving outreach on underperforming channels, and addressing cancellation issues through targeted measures.

**9. Competitive Advantage:**

Utilizing data-driven insights allows hotels to gain a competitive edge in the market. By understanding customer preferences, optimizing pricing, and aligning marketing efforts with seasonal trends, hotels can position themselves strategically to attract more guests and achieve higher revenue compared to their competitors.

While the analysis provided valuable insights, it is essential to continuously monitor and update the analysis based on changing market dynamics and evolving customer behaviors. Additionally, integrating external data sources, such as market trends and competitor analysis, can further enhance the depth and accuracy of the analysis.

The findings from the EDA will be summarized in a comprehensive report, supported by clear visualizations and actionable insights. The report will highlight key trends, patterns, and recommendations based on the data analysis. These insights can be leveraged by hotel management to optimize pricing strategies, improve customer satisfaction, and enhance overall operational efficiency.

# **Problem Statement**


Q1) Which agent makes the most no. of bookings?

 Q2) Which room type is in most demand and which room type generates the highest ADR?

 Q3) Which meal type is the most preferred meal for customers?

 Q4) What is the percentage of bookings in each hotel?

 Q5) Which is the most common channel for booking hotels?

 Q6) Which are the busiest months?

 Q7) From which country most of the guests are coming?

 Q8) How long do people stay at the hotels?

 Q9) Which hotel seems to make more revenue?

 Q10) Which hotel has a higher lead time?

 Q11) What is the preferred stay length in each hotel?

 Q12) Which hotel has a higher bookings cancellation rate?

 Q13) Which hotel has a high chance that its customer will return for another stay?

 Q14) Which channel is mostly used for the early booking of hotels?

 Q15) Which channel has a longer average waiting time?

 Q16) Which distribution channel brings better revenue-generating deals for hotels?

 Q17) Which significant distribution channel has the highest cancellation percentage?

 Q18) Does a longer waiting period or longer-lead time causes the cancellation of bookings?

 Q19) Whether not getting allotted the same room type as demand the main cause of cancellation for bookings?

 Q20) Does not allowing the same room as demanded to affect ADR?

#### **Define Your Business Objective?**

The objective of this project is to perfrom an EDA on hotel booking dataset to gain some insights which will be helpful in understanding the patterns and trends in booking analysis, cancellation analysis, Revnue analysis, customer segmentation and competitive analysis.
The valuable insights gained will be helpful in improving the operational efficiency, better finance management, increasing revnue, support data-driven decision-making and competitive positioning.

# ***Let's Begin !***

## ***1. Know your Data***


Import libraries


In [1]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Dataset loading


In [ ]:
# mounting drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# reading the Dataset
path = "/content/drive/MyDrive/capstone project data/Hotel Bookings.csv"
hotel_df = pd.read_csv(path)

Data set first **look**

In [ ]:
hotel_df.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

Dataset Information

In [ ]:
# Dataset Info
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

 Null values

In [ ]:
# null values
null_values = hotel_df.isnull().sum()
print(null_values)

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

We see that there are 32 columns in the dataframe and some columns like 'children', 'company', 'country', and 'agent' have null values.

## **2. Understanding your variables**

In [ ]:
# Dataset description
hotel_df.describe()

### Check unique values for each variable

In [ ]:
# creating copy of Dataframe
df1 = hotel_df.copy()

In [ ]:
# unique values
df1['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [ ]:
df1['is_canceled'].unique()

array([0, 1])

In [ ]:
df1['arrival_date_year'].unique()

array([2015, 2016, 2017])

In [ ]:
df1['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [ ]:
df1['market_segment'].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [ ]:
df1['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [ ]:
df1['children'].unique()

array([ 0.,  1.,  2., 10.,  3., nan])

### Variables Description

1. **hotel**: Categorical - Resort hotel or city hotel.
2.	**is_canceled**: ‘1’ for booking and ‘0’  not cancelled.
3.	**lead_time**: Period between time of booking and checking in (considered in days here).
4.	**arrival_date_month**: Arrival month
5.	**country**: Country of origin. List of 158 countries.
6.	**days_in_waiting_list**: Number of waiting days.
7.	**Deposit_type**: Categorical - No-deposit, Non-Refund, Refundable.
8.	**Adr**: Average Daily rate as defined by the average rental revenue earned for an occupied room per day.
9.	**Adults, Babies, Children**: Number of adults, babies and children.
10.	**Assigned Room Type**: Code for the type of room assigned to the booking.
11.	**Booking Changes**: Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation.
12.	**Distribution_channel**: Booking distribution channel.
13.	**Is_repeated_guest’**: Categorical- repeated guest(1) or not (0).
14.	**Company**: ID of the company/entity that made the booking or responsible for paying the booking.
15.	**Customer Type**: Categorical:
- Contract – when the booking has an allotment or other type of contract
associated to it
- Group – when the booking is associated to a group;
- Transient – when the bookings is not part of a group or contract, and is not associated to other transient booking;
- Transient party – when the booking is transient to at least other transient booking.
16.	**Market_segment**: Market segment designation.
17.	**Previous_cancellations**: Number of previous bookings that were cancelled by the customer prior to the current booking.
18.	**Required_car_parking_spaces**: Number of car parking spaces required by the customer.
19.	**Reservation_status**:Categorical:
- Cancelled – booking was cancelled by the customer.
- Check Out – customer has checked in but already departed.
- No Show – customer did not check in and did inform the hotel of the reason why.
20.	**Reservation_status_date**: Date at which the last status was set. This variable can be used in conjunction with the Reservation Status to understand when was the booking canceled or when did the customer checked-out of the hotel.
21.	**Reserved_room_type**: Code of room type reserved.
22.	**Types_of_special_requests**: Number of special requests made by the customer (e.g. Twin bed or high floor)
23.	**Stays_in_weekend_nights**, **Stays_in_week_nights**: Number of weekend nights and week nights the guest stayed or booked to stay at the hotel.


First of all we will try to understand the meaning of all columns of the dataframe.
For this we will see the unique values attained by each column whose meaning we are unable to understand.

## **3. Data wrangling**

Data Wrangling is crucial step before EDA as it will remove the ambigous data that can affect the outcome of EDA.
1. Remove duplicate rows.
2. Handling missing values.
3. Convert columns to appropriate datatypes.
4. Adding important columns

#### Step 1: Removing duplicate rows if any

In [ ]:
# Show no. of rows of duplicate rows duplicate rows
df1[df1.duplicated()].shape

(31994, 32)

In [ ]:
# Dropping duplicate values
df1.drop_duplicates(inplace = True)

In [ ]:
df1.shape

(87396, 32)

#### Step 2. Handling missing value.

In [ ]:
# columns having missing values
df1.isnull().sum().sort_values(ascending = False)[:6]

company               82137
agent                 12193
country                 452
children                  4
reserved_room_type        0
assigned_room_type        0
dtype: int64

Since, company and agent columns have company number and agent numbers as data. There may be some cases when     customer didnt booked hotel via any agent or via any company. So in that case values can be null under these columns.
We will replace null values by 0 in these columns.

In [ ]:
df1[['company','agent']] = df1[['company','agent']].fillna(0)

In [ ]:
df1['children'].unique()

array([ 0.,  1.,  2., 10.,  3., nan])

This column 'children' has 0 as value which means 0 children were present in group of customers who made that transaction.
So, 'nan' values are the missing values due to error of recording data.
We will replace the null values under this column with mean value of children.

In [ ]:
df1['children'].fillna(df1['children'].mean(), inplace = True)

Next column with missing value is 'country'. This column represents the country of origin of customer.
Since this column has datatype of string. We will replace the missing value with the mode of 'country' column.

In [ ]:
 df1['country'].fillna('others', inplace = True)

In [ ]:
#checking if all null values are removed
df1.isnull().sum().sort_values(ascending = False)[:6]

hotel                          0
is_canceled                    0
reservation_status             0
total_of_special_requests      0
required_car_parking_spaces    0
adr                            0
dtype: int64

There are some rows with total number of adults, children or babies equal to zero.So we will replace such rows

In [ ]:
df1[df1['adults']+df1['babies']+df1['children'] == 0].shape

(166, 32)

In [ ]:
df1.drop(df1[df1['adults']+df1['babies']+df1['children'] == 0].index, inplace = True)

#### Step 3: Converting columns to appropriate datatypes

In [ ]:
# converting datatype of columns 'children', 'agent', and 'company'from float to int.
df1[['children','company','agent']] = df1[['children', 'company', 'agent']].astype('int64')

#### Step: 4 Adding important columns

In [ ]:
#Adding total staying in hotels
df1['total_stay'] = df1['stays_in_weekend_nights'] + df1['stays_in_week_nights']

In [ ]:
# adding total people num as column, i.e. total people num = num of adults + children + babies
df1['total_people'] = df1['adults'] + df1['children'] + df1['babies']

We are adding this column so that we can analyse th stay lenght at hotels.